# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true
[[social]]
identifier = "Main Page"
url = "https://sounddrill31.github.io"

[social.params]
icon = "home"

[[social]]
identifier = "lab"
url = "https://lab.sounddrill31.github.io/tgl"

[social.params]
icon = "infinity"

[[social]]
identifier = "blog"
[social.params]
icon = "archives"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/sounddrill31"

[social.params]
icon = "brand-github"

[[social]]
identifier = "RSS"
url = "/post/index.xml"

[social.params]
icon = "rss"