name: Deploy to Github Pages

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    discussion:
        types: [created, edited]
jobs:
    build:
        permissions:
          contents: write
          pages: write
          id-token: write
        runs-on: ubuntu-latest
        if: github.event_name != 'discussion' || github.event.discussion.category.name == 'Announcements'

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'

            - name: Install Python dependencies
              run: |
                  pip install requests PyYAML

            - name: Fetch Discussions and Convert to Markdown
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  python .github/scripts/discussions_to_markdown.py || true

            - name: Cache Hugo resources
              uses: actions/cache@v4
              env:
                  cache-name: cache-hugo-resources
              with:
                  path: resources
                  key: ${{ env.cache-name }}

            - uses: actions/setup-go@v5
              with:
                  go-version: "^1.17.0"
            - run: go version

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"
                  extended: true

            - name: Build
              run: hugo --minify --gc

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: public
                  clean: true
                  single-commit: true
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}